controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

slider_item:
    resource: '../src/Controller/SliderItemController.php'
    type: attribute
