controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

feedback_submit:
    path: /submit-feedback
    controller: App\Controller\FeedbackController::submitFeedback
